const data = {
    products: [
      {
        _id: '1',
        name: 'Jacket',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 19,
        countInStock: 17,
        brand: 'tsho',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'vest',
        category: 'bag',
        image: '/images/p2.jpg',
        price: 100,
        countInStock: 12,
        brand: 'hima',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'cap',
        category: 'watch',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 9,
        brand: 'rioswatch',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality ',
      },
      {
        _id: '4',
        name: 'sunny glass',
        category: 'glass',
        image: '/images/p4.jpg',
        price: 78,
        countInStock: 0,
        brand: 'glassy',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality ',
      },
      {
        _id: '5',
        name: 'hat ',
        category: 'band',
        image: '/images/p3.jpg',
        price: 65,
        countInStock: 2,
        brand: 'banner',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality ',
      },
      {
        _id: '6',
        name: 'b-cap',
        category: 'rubiks',
        image: '/images/p1.jpg',
        price: 139,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },
      {
        _id: '7',
        name: 'jacket',
        category: 'jimm',
        image: '/images/p1.jpg',
        price: 99,
        countInStock: 6,
        brand: 'jiky',
        rating: 4,
        numReviews: 15,
        description: 'good product',
      },
    ],
  };
  
  export default data;