const data = {
    products: [
      {
        _id: '1',
        name: 'red shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 14,
        countInStock: 10,
        brand: 'tsho',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'yo bag',
        category: 'bag',
        image: '/images/p2.jpg',
        price: 100,
        countInStock: 20,
        brand: 'hima',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'rio watch',
        category: 'watch',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 0,
        brand: 'rioswatch',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality ',
      },
      {
        _id: '4',
        name: 'sunny glass',
        category: 'glass',
        image: '/images/p4.jpg',
        price: 78,
        countInStock: 15,
        brand: 'glassy',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality ',
      },
      {
        _id: '5',
        name: 'wearable ',
        category: 'band',
        image: '/images/p3.jpg',
        price: 65,
        countInStock: 5,
        brand: 'banner',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality ',
      },
      {
        _id: '6',
        name: 'cube',
        category: 'rubiks',
        image: '/images/p1.jpg',
        price: 139,
        countInStock: 12,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },
    ],
  };
  
  export default data;