export default  [
      {
        _id: '1',
        name: 'shirt',
        category: 'clothes',
        image: '/images/p1.jpg',
        price: 8,
        countInStock: 17,
        brand: 'tsho',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'vest',
        category: 'clothes',
        image: '/images/p2.jpg',
        price: 100,
        countInStock: 12,
        brand: 'hima',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'black cap',
        category: 'clothes',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 9,
        brand: 'rioswatch',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality ',
      },
      {
        _id: '4',
        name: 'sunny hat',
        category: 'clothes',
        image: '/images/p4.jpg',
        price: 78,
        countInStock: 0,
        brand: 'glassy',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality ',
      },
      {
        _id: '5',
        name: 'shoe',
        category: 'shoes',
        image: '/images/shoe11.jpeg',
        price: 65,
        countInStock: 2,
        brand: 'banner',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality ',
      },

      {
        _id: '6',
        name: 'shoes',
        category: 'shoes',
        image: '/images/shoe2.jpeg',
        price: 65,
        countInStock: 2,
        brand: 'banner',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality ',
      },

      {
        _id: '7',
        name: 'shoe',
        category: 'shoes',
        image: '/images/shoe22.jpeg',
        price: 65,
        countInStock: 2,
        brand: 'banner',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality ',
      },

      {
        _id: '8',
        name: 'shoe',
        category: 'shoes',
        image: '/images/shoe3.jpeg',
        price: 65,
        countInStock: 2,
        brand: 'banner',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality ',
      },
      {
        _id: '9',
        name: 'a-laptop',
        category: 'laptop',
        image: '/images/pc.jpeg',
        price: 139,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },

      {
        _id: '10',
        name: 'h-laptop',
        category: 'laptop',
        image: '/images/pc3.jpeg',
        price: 139,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },
      {
        _id: '11',
        name: 'b-laptop',
        category: 'laptop',
        image: '/images/pc22.jpeg',
        price: 139,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      }
      ,
      {
        _id: '12',
        name: 'b-watch',
        category: 'watch',
        image: '/images/watch1.jpeg',
        price: 139,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      }
      ,
      {
        _id: '13',
        name: 'b-watch',
        category: 'watch',
        image: '/images/watch33.jpeg',
        price: 139,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      }
      ,
      {
        _id: '14',
        name: 'y-watch',
        category: 'watch',
        image: '/images/watch55.jpeg',
        price: 99,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      }
      ,
      {
        _id: '15',
        name: 'women-bag',
        category: 'bag',
        image: '/images/bag0.jpeg',
        price: 19,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      }
      ,
      {
        _id: '16',
        name: 'women-bag',
        category: 'bag',
        image: '/images/bag34.jpeg',
        price: 19,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      }

      ,
      {
        _id: '15',
        name: 'women-bag',
        category: 'bag',
        image: '/images/bag23.jpeg',
        price: 19,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },
      {
        _id: '15',
        name: 'books',
        category: 'books',
        image: '/images/books.jpeg',
        price: 19,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },
      {
        _id: '15',
        name: 'books',
        category: 'books',
        image: '/images/books.jpeg',
        price: 19,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },
      {
        _id: '15',
        name: 'books',
        category: 'books',
        image: '/images/mbook.png',
        price: 19,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },

      {
        _id: '15',
        name: 'books',
        category: 'books',
        image: '/images/ooks3.jpeg',
        price: 19,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },

      {
        _id: '15',
        name: 'phone',
        category: 'phone',
        image: '/images/phone1.jpeg',
        price: 19,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      },

      {
        _id: '15',
        name: 'phone',
        category: 'phone',
        image: '/images/phone2.jpeg',
        price: 19,
        countInStock: 6,
        brand: 'tyo',
        rating: 4.5,
        numReviews: 15,
        description: 'good product',
      }

];